version: '3'

services:
  app: 
    image: troddit
    build:
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
      - 4321:4321
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDDIT_REDIRECT=${REDDIT_REDIRECT}
      - SIGNING_PRIVATE_KEY=${SIGNING_PRIVATE_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - COPILOT_CLI_PORT=4321
